### ISSUE TITLE
[Forge 1.19.2] Crash when looking at Swat armor in inventory or in third person.

### ISSUE THREAD

**Issue by falfalos** [MarbledFoxx/Marbleds-Arsenal-1.20.1#2]
What the title says. However, it does not crash the game to wear the armor, only whenever it is looked at while worn on the player. Clearing the player's inventory of Swat armor fixes the issue.

[These are my logs.](https://mclo.gs/HtNSZgW) I only have Geckolib and Marbled's Arsenal 2.0.2 enabled on a fresh install of forge 1.19.2

**Comment by MarbledFoxx** [comment]
Thanks for reporting! The armor has been fixed in 2.0.3 which will be released soon.
